### PR TITLE
Add a scons SConstruct file for building and installing the library

### PR DESCRIPTION
**Pull request by mattpitkin**
Hi Brendon,

I've created a SContruct file for installing and building the library with scons in case this is useful to people. Running with
`scons install`
will install in `/usr/local` by default (provided root permissions are available), but otherwise the install location can be set with the `--prefix` command. At the moment this does not compile the examples.

Cheers,

Matt

### CODE REVIEW

**Comment by mattpitkin** [comment]
Hi @eggplantbren - do you think you'll consider adding this scons build method, or should I close the request? I can update the README file to describe the installation method (and its current limitations).

**Comment by eggplantbren** [comment]
Sorry for the delay. If you put a section in the README about this way of building it then I'll check it out, try it, and probably merge.

**Comment by mattpitkin** [comment]
I've updated the README file. Let me know if it looks ok.

**Comment by eggplantbren** [comment]
All good; merged.

**Comment by mattpitkin** [comment]
Great, thanks very much.

**Pull request merged**
