### PR TITLE
New distributions

### PR DESCRIPTION
**Pull request by j-faria**
I added a couple of new distributions and their truncated versions.
Feel free to rename Jeffreys -> Reciprocal, or something like that if you want: that name stuck in the exoplanet field but it's not the best.
I also changed the makefile to not recompile every time and to not compile the examples by default.

### CODE REVIEW

**Comment by eggplantbren** [comment]
Would you mind if I change some things before accepting this?

**Comment by j-faria** [comment]
Of course not :)

**Comment by eggplantbren** [comment]
One of those things will be to rename Jeffreys to LogUniform ;-), but you can just put a using declaration in kima to make it an alias.

`using Jeffreys = LogUniform;`

or

`typedef LogUniform Jeffreys;`

ought to work.

**Comment by eggplantbren** [comment]
Okay, I did rename it but I put the alias in there as well so you needn't change anything in kima.

**Comment by j-faria** [comment]
Awesome!
But if you change your mind, I also think LogUniform makes total sense.
With this it should be much easier to keep things up to date in kima. Thank you!

**Pull request merged**
